controllers/AdminController.php
<?php
namespace app\controllers;

use app\models\Datawidget;
use app\models\ListMenu;
use app\models\Listwidget;
use app\models\ListwidgetSearch;
use app\models\NewUserForm;
use app\models\PasswordResetForm;
use app\models\Request;
use app\models\User;
use Yii;
use yii\base\Model;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class AdminController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [

                        'controllers' => ['admin/login'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function beforeAction($action)
    {


        if ((Yii::$app->user->isGuest)and($action->id !== 'login')) {
            return $this->redirect(['login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {

        $model = Request::find()->orderBy('create_date')->all();



        return $this->render('index', [
            'model' => $model,
        ]);

    }
    public function actionRereq($id)
    {
        $model = $this->findRequest($id);
        $model->load(Yii::$app->request->post());
        $model->processed = 'close';
        $model->save();
        return $this->redirect(['index', 'id' => $model->id]);
    }

    public function actionDelreq($id)
    {
        $model = $this->findRequest($id);
        $model->delete();
        return $this->redirect(['index', 'id' => $model->id]);
    }

    public function actionNew()
    {


        $model = new Listwidget();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);

    }

    public function actionCreatedata($userId)
    {
        $widget = $this->findModel($userId);
        $model = new Datawidget();
        $model->addOne($userId);
        $widget->link('datawidgets', $model); // link сохраняет в базу данных без валидации, будьте осторожны
        return $this->renderAjax('_form'. $widget->tampl, ['model' => $widget]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    protected function batchUpdate($items)
    {
        if (Model::loadMultiple($items, Yii::$app->request->post()) &&
            Model::validateMultiple($items)) {
            foreach ($items as $key => $item) {

                $item->save();

            }
        }
    }

    protected function batchDelete($items)
    {
        if (Model::loadMultiple($items, Yii::$app->request->post()) &&
            Model::validateMultiple($items)) {
            foreach ($items as $key => $item) {
                $item->delete();
            }
        }
    }


    public function actionPosition()
    {

        $model = Listwidget::find()->orderBy('position')->all();

        return $this->render('position', [

            'model' => $model ,
        ]);
    }

    public function actionUpdatepos()
    {

        $widget = Listwidget::find()->orderBy('position')->all();
        $this->batchUpdate($widget);
        return $this->redirect(['position']);
    }

    public function actionDelete($id)
    {
        $widget = $this->findModel($id);
        $this->batchDelete($widget->datawidgets);
        $widget->delete();
        return $this->redirect(['index']);
    }


    public function actionDeleteall($id)
    {
        $model = $this->findDataWidget($id);
        $widget = $model->widget;
        $model->delete();
        return $this->renderAjax('_form' . $widget->tampl, ['model' => $widget]);
    }

    public function actionUpdatedata($userId)
    {
        $widget = $this->findModel($userId);
        $widget->load(Yii::$app->request->post()) && $widget->save();
        $this->batchUpdate($widget->datawidgets);
        return $this->renderAjax('_form' . $widget->tampl, ['model' => $widget]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }



    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionUserlist()
    {
        $model = User::find()->all();
        return $this->render('userlist', [
            'model' => $model,
        ]);
    }

    public function actionNewuser(){

        $model = new NewUserForm();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['admin/userlist']);
        }

        return $this->render('newuserform', [
            'model' => $model,
        ]);
    }

    public function actionDeluser($token)
    {
        $model =  User::findByAythkey($token);
        $model->delete();
        return $this->redirect(['admin/userlist']);
    }

    public function actionPassreset($token)
    {
        $model = new PasswordResetForm($token);
        if ($model->load(Yii::$app->request->post()) && $model->resetPassword()) {
            return $this->redirect(['admin/userlist']);
        }

        return $this->render('passresetform', [
            'model' => $model,
        ]);

    }


    public function actionLogin()
    {



        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['index']);
        }

        $this->layout = '//main-login';
        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['index']);
    }



    protected function findRequest($id)
    {
        if (($model = Request::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findModel($id)
    {
        if (($model = Listwidget::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findDataWidget($id)
    {
        if (($model = Datawidget::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }




}

views/admin/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */
?>

views/admin/_form_img.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */
?>



    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'label')->textInput() ?>

    <?= $form->field($model, 'type')->dropDownList([ 'Y' => 'Y', 'N' => 'N', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'idname')->textInput() ?>

    <img src="<?= $model->data ?>" width="100%">

    <?= $form->field($model, 'data')->widget(InputFile::className(), [
        'language'      => 'ru',
        'controller'    => 'elfinder', // вставляем название контроллера, по умолчанию равен elfinder

        'filter'        => 'image',    // фильтр файлов, можно задать массив фильтров https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#wiki-onlyMimes
        'template'      => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
        'options'       => ['class' => 'form-control'],
        'buttonOptions' => ['class' => 'btn btn-success'],
        'multiple'      => false       // возможность выбора нескольких файлов
    ]);?>




    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

views/admin/_form_listwidget.php
<?php

use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;
use  app\models\Listwidget;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */

?>

<?php

Pjax::begin(['enablePushState' => false]);

?>

<?php $form = ActiveForm::begin([
    'action' => Url::toRoute(['admin/updatedata', 'userId' => $model->id]),
    'options' => [
        'data-pjax' => '1'
    ],
    'id' => 'UpdateForm'
]); ?>



    <?= $form->field($model, 'label')->textInput() ?>

    <?= $form->field($model, 'type')->dropDownList([ 'Y' => 'Y', 'N' => 'N', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'idname')->textInput() ?>






<?php
    foreach ($model->datawidgets as $id => $datawidget) {?>
    <div class="col-md-4">
            <div class="box box-solid box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Слайд <?= $id + 1 ?></h3>
                        <div class="box-tools pull-right">
                        </div>
                 </div>
                 <div class="box-body">
        <?=  $form->field($datawidget, '[' . $id . ']title')->textInput() ?>

                     <img src="<?= $datawidget->src ?>" width="100%" >

        <?= $form->field($datawidget, '[' . $id . ']src')->widget(InputFile::className(), [
            'language'      => 'ru',
            'controller'    => 'elfinder',

            'filter'        => 'image',
            'template'      => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
            'options'       => ['class' => 'form-control'],
            'buttonOptions' => ['class' => 'btn btn-success'],
            'multiple'      => false
        ]);?>

                     <?=  $form->field($datawidget, '[' . $id . ']description')->textarea(['rows' => 5, 'cols' => 5]) ?>

        <?= Html::a('Удалить', Url::toRoute(['admin/deleteall', 'id' => $datawidget->id]), [
            'class' => 'btn btn-danger',
        ]) ?>


                 </div>
            </div>
    </div>

    <?php
    }

?>
<div class="col-md-12">
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Добавить', Url::toRoute(['admin/createdata', 'userId' => $model->id]), [
            'class' => 'btn btn-success',
        ]) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

<?php Pjax::end(); ?>

views/admin/_form_mainwidget.php
<?php

use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;
use  app\models\Listwidget;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */

?>








<?php Pjax::begin(['enablePushState' => false]);?>

<?php $form = ActiveForm::begin([
    'action' => Url::toRoute(['admin/updatedata', 'userId' => $model->id]),
    'options' => [
        'data-pjax' => '1'
    ],
    'id' => 'UpdateForm'
]); ?>



    <?= $form->field($model, 'label')->textInput() ?>

    <?= $form->field($model, 'type')->dropDownList([ 'Y' => 'Y', 'N' => 'N', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'idname')->textInput() ?>






<?php
    foreach ($model->datawidgets as $id => $datawidget) {?>
    <div class="col-md-4">
            <div class="box box-solid box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Слайд <?= $id + 1 ?></h3>
                        <div class="box-tools pull-right">
                        </div>
                 </div>
                 <div class="box-body">
        <?=  $form->field($datawidget, '[' . $id . ']title')->textInput() ?>

                     <img src="<?= $datawidget->data ?>" width="100%">

        <?= $form->field($datawidget, '[' . $id . ']data')->widget(InputFile::className(), [
            'language'      => 'ru',
            'controller'    => 'elfinder', // вставляем название контроллера, по умолчанию равен elfinder

            'filter'        => 'image',    // фильтр файлов, можно задать массив фильтров https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#wiki-onlyMimes
            'template'      => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
            'options'       => ['class' => 'form-control'],
            'buttonOptions' => ['class' => 'btn btn-success'],
            'multiple'      => false       // возможность выбора нескольких файлов
        ]);?>

        <?= Html::a('Удалить', Url::toRoute(['admin/deleteall', 'id' => $datawidget->id]), [
            'class' => 'btn btn-danger',
        ]) ?>


                 </div>
            </div>
    </div>

    <?php
    }

?>
<div class="col-md-12">
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Добавить', Url::toRoute(['admin/createdata', 'userId' => $model->id]), [
            'class' => 'btn btn-success',
        ]) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

<?php Pjax::end(); ?>

views/admin/_form_map.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */
?>



    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'label')->textInput() ?>

    <?= $form->field($model, 'type')->dropDownList([ 'Y' => 'Y', 'N' => 'N', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'idname')->textInput() ?>

    <script type="text/javascript" charset="utf-8" async src="<?= $model->data ?>"></script>

    строка из джава скрипта только ссылка и удалите атрибут ширины. без него точно лучше
    <?= $form->field($model, 'data')->textInput() ?>



    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

views/admin/_form_sale.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */
?>



    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'label')->textInput() ?>

    <?= $form->field($model, 'type')->dropDownList([ 'Y' => 'Y', 'N' => 'N', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'idname')->textInput() ?>

    <?= $form->field($model, 'data')->widget(CKEditor::className(), [
        'editorOptions' => ElFinder::ckeditorOptions('elfinder',[]),
        'options' => ['higth' => 100],
    ])->label(false);?>




    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

views/admin/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\models\Request;

/* @var $this yii\web\View */
/* @var $model app\models\Request */

$this->title = 'Админка';
?><div class="box">
    <div class="box-header">
        <h3 class="box-title">Таблица заявок</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">
        <table class="table table-striped">
            <tbody><tr>
                <th style="width: 10px">#</th>
                <th>Имя</th>
                <th>Номер телефона</th>
                <th>Описание</th>
                <th>Время создания</th>
                <th style="width: 30px">Статус</th>
                <th style="width: 180px"></th>
            </tr>
   <?php foreach ($model as $key => $item) { ?>
       <tr>
           <td><?= Html::encode($key)?></td>
           <td><?= Html::encode($item->name)?></td>
           <td><?= Html::encode($item->phone)?></td>
           <td><?= Html::encode($item->descript)?></td>
           <td><?= Html::encode($item->create_date)?></td>
           <td>
           <?php if($item->processed){?>
               <span class="badge ">ok</span></td>
           <?php }else{ ?>
               <span class="badge bg-red">NEW</span></td>
           <?php }; ?>
           <td>  <?= Html::a('Закрыть', Url::toRoute(['admin/rereq', 'id' => $item->id]), [
               'class' => 'btn btn-info',
           ]) ?>
           <?= Html::a('Удалить', Url::toRoute(['admin/delreq', 'id' => $item->id]), [
               'class' => 'btn btn-warning',
           ]) ?></td>
       </tr>

   <?php }  ?>



            </tbody></table>
    </div>
    <!-- /.box-body -->
</div>

views/admin/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <img src="/css/img/login_logo.png">
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Пройдите авторизацию что бы продолжить</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>


    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

views/admin/newuserform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Новый пользователь';
?>



    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'username')->textInput()?>
    <?= $form->field($model, 'password')->passwordInput()?>
    <?= $form->field($model, 'password_repeat')->passwordInput()?>

        <?= Html::submitButton('Cохранить', ['class' => 'btn btn-success']) ?>



    <?php ActiveForm::end(); ?>

views/admin/passresetform.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Сменить пароль';
?>



    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'password')->passwordInput()?>
    <?= $form->field($model, 'password_repeat')->passwordInput()?>

        <?= Html::submitButton('Cохранить', ['class' => 'btn btn-success']) ?>



    <?php ActiveForm::end(); ?>

views/admin/position.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\web\View;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $searchModel app\models\listWidget */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Очередность виджетов';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-8">





        <div class="box  box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
                <div class="box-tools pull-right">
                </div>
            </div>
            <div class="box-body container ">
                <h4>
    <?php
    $form = ActiveForm::begin( ['action' => Url::toRoute(['admin/updatepos']),]);
    foreach ($model as $key => $item){?>
        <div  class="drag " id= '<?= Html::encode($key) ?>' style="border-bottom: 1px solid #0b3e6f; padding: 10px; width: 70%;"> <?= Html::encode($item->label) ?></div>

    <?php } ?>
                </h4>
            </div>
        </div>
    <div id="pos-list">
    <?php foreach ($model as $key => $item){?>
        <?= $form->field($item, '[' . $key . ']position')->hiddenInput()->label(false) ?>
        <?= $form->field($item, '[' . $key . ']id')->hiddenInput()->label(false) ?>
    <?php } ?>
    </div>
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success',
                                                'id' => 'pos',
                                                'name' => 'yii'
                                                                            ]) ?>

    <?php $form = ActiveForm::end();

    ?>


</div>

views/admin/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */

$this->title = 'Редактирование виджета: id' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Виджет id' . $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Редактор виджета</h3>
        <div class="box-tools pull-right">

        </div>
        <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body">






    <?= $this->render('_form' . $model->tampl, [
        'model' => $model,
    ]) ?>

</div>
</div>

views/admin/userlist.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\models\Request;

/* @var $this yii\web\View */
/* @var $model app\models\Request */

$this->title = '';
?><div class="box">
    <div class="box-header">
        <h3 class="box-title">Пользователи</h3> <?= Html::a('Новый', Url::toRoute(['admin/newuser']), [
            'class' => 'btn btn-success',
        ]) ?>
    </div>

    <!-- /.box-header -->
    <div class="box-body no-padding">
        <table class="table table-striped">
            <tbody><tr>
                <th style="width: 10px">#</th>
                <th>Логин</th>
                <th>Создан</th>
                <th>Изменен</th>


                <th style="width: 240px"></th>
            </tr>
   <?php foreach ($model as $key => $item) { ?>
       <tr>
           <td><?= Html::encode($key)?></td>
           <td><?= Html::encode($item->username)?></td>

           <td><?= Html::encode(Yii::$app->formatter->asDatetime($item->created_at)) ?></td>
           <td><?= Html::encode(Yii::$app->formatter->asDatetime($item->updated_at))?></td>

           <td>  <?= Html::a('Сменить пароль', Url::toRoute(['admin/passreset', 'token' => $item->authKey]), [
               'class' => 'btn btn-info',
           ]) ?>
           <?= Html::a('Удалить', Url::toRoute(['admin/deluser', 'token' => $item->authKey]), [
               'class' => 'btn btn-danger',
           ]) ?></td>
       </tr>

   <?php }  ?>



            </tbody></table>
    </div>

    <!-- /.box-body -->
</div>

views/admin/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Listwidget */

$this->title = 'Виджет id' . $model->id;
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="listwidget-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'position',
            'data:ntext',
            'type',
            'idname:ntext',
            'tampl:ntext',
        ],
    ]) ?>

</div>